apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: secret-demo-jetstack-net
  renewBefore: 360h # 15d
  commonName: demo.jetstack.net
  dnsNames:
  - demo.jetstack.net
  issuerRef:
    name: issuer
    kind: Issuer
  acme:
    config:
    - http01:
        ingress: ingress
      domains:
      - demo.jetstack.net
