apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../helloweb-cert

namespace: helloweb

commonLabels:
  app: helloweb
  demo: kustomize-cert-manager

# Create secrets/tls.crt and secrets/tls.key files to use as a CA
secretGenerator:
  - name: helloweb-ca
    files:
      - secrets/tls.crt
      - secrets/tls.key
    type: "kubernetes.io/tls"

generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resource: somevalue

resources:
  - issuer.yaml
