apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../helloweb-cert

namespace: helloweb

commonLabels:
  app: helloweb
  demo: kustomize-cert-manager

resources:
  - issuer.yaml

# Uncomment to use the production Let's Encrypt server
#patchesJSON6902:
#  - path: issuer_patch_letsencrypt_prod.json
#    target:
#      group: cert-manager.io
#      version: v1
#      kind: Issuer
#      name: helloweb-issuer
