apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../helloweb-cert

namespace: helloweb

commonLabels:
  app: helloweb
  demo: kustomize-cert-manager

resources:
  - issuer.yaml

# Create this patch to set the Issuer email
patchesJSON6902:
  - path: issuer_patch.json
    target:
      group: cert-manager.io
      version: v1
      kind: Issuer
      name: helloweb-issuer